repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.89.1
    hooks:
      - id: terraform_validate
        args:
          - --hook-config=--retry-once-with-cleanup=true
          - --tf-init-args=-upgrade
        files: '../'
        exclude: '(\.)?modules/'

      - id: terraform_providers_lock
        args:
        - --hook-config=--mode=always-regenerate-lockfile
        - --args=-platform=darwin_arm64
        files: '../'
        exclude: '(\.)?modules/'
